/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_dravyaengine_free: (a: number, b: number) => void;
export const batch_calculate_implied_volatility: (a: number, b: number) => [number, number, number, number];
export const benchmark_simd_greeks: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const calculate_binomial_tree: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const calculate_implied_volatility: (a: number, b: number, c: number, d: number, e: number) => number;
export const deterministicSeedLog: (a: number) => void;
export const dravyaengine_new: () => number;
export const dravyaengine_sort_colors: (a: number, b: number, c: number, d: any) => [number, number];
export const dravyaengine_sort_colors_with_history: (a: number, b: number, c: number) => [number, number, number];
export const dravyaengine_step_count: (a: number) => number;
export const generate_sabr_surface: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const generate_vol_surface: (a: number, b: number, c: number, d: number, e: number) => any;
export const get_wasm_memory_size: () => number;
export const price_heston_american: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number];
export const price_heston_european: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number];
export const price_monte_carlo_gpu: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const sort_colors: (a: number, b: number, c: any) => void;
export const sort_colors_with_history: (a: number, b: number) => any;
export const vannaVolgaAdjustment: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const __wbg_arrowmemorypointer_free: (a: number, b: number) => void;
export const __wbg_get_arrowmemorypointer_array_ptr: (a: number) => number;
export const __wbg_get_arrowmemorypointer_data_ptr: (a: number) => number;
export const __wbg_get_arrowmemorypointer_length: (a: number) => number;
export const __wbg_get_arrowmemorypointer_schema_ptr: (a: number) => number;
export const __wbg_set_arrowmemorypointer_array_ptr: (a: number, b: number) => void;
export const __wbg_set_arrowmemorypointer_data_ptr: (a: number, b: number) => void;
export const __wbg_set_arrowmemorypointer_length: (a: number, b: number) => void;
export const __wbg_set_arrowmemorypointer_schema_ptr: (a: number, b: number) => void;
export const loadParquetToMemory: (a: number, b: number) => number;
export const zeroCopyBufferView: (a: number, b: number) => number;
export const wasm_bindgen_39059793c51de849___closure__destroy___dyn_core_2be32f71e062320c___ops__function__FnMut__wasm_bindgen_39059793c51de849___JsValue____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_39059793c51de849___closure__destroy___dyn_core_2be32f71e062320c___ops__function__FnMut__wasm_bindgen_39059793c51de849___JsValue____Output___core_2be32f71e062320c___result__Result_____wasm_bindgen_39059793c51de849___JsError___: (a: number, b: number) => void;
export const wasm_bindgen_39059793c51de849___convert__closures_____invoke___wasm_bindgen_39059793c51de849___JsValue__core_2be32f71e062320c___result__Result_____wasm_bindgen_39059793c51de849___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_39059793c51de849___convert__closures_____invoke___js_sys_765e3a270b859b1f___Function_fn_wasm_bindgen_39059793c51de849___JsValue_____wasm_bindgen_39059793c51de849___sys__Undefined___js_sys_765e3a270b859b1f___Function_fn_wasm_bindgen_39059793c51de849___JsValue_____wasm_bindgen_39059793c51de849___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_39059793c51de849___convert__closures_____invoke___wasm_bindgen_39059793c51de849___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_39059793c51de849___convert__closures_____invoke___wasm_bindgen_39059793c51de849___JsValue______true__1: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
